#! python3
# downloadXkcd.py - Downloads every single XKCD comic.

import requests, os, bs4

# Starting URL
url = 'http://xkcd.com'
# Ensure ./xkcd folder exists
os.makedirs('xkcd', exist_ok=True)

# Loop until we reach the first comic page, where the Prev button's URL ends with '#'
while not url.endswith('#'):
    # Download the current page
    print(f'Downloading page {url}...')
    res = requests.get(url)
    res.raise_for_status()

    # Parse the page with BeautifulSoup
    soup = bs4.BeautifulSoup(res.text, 'html.parser')

    # Find the comic image URL
    comicElem = soup.select('#comic img')
    if comicElem == []:
        print('Could not find comic image.')
    else:
        # Build the full comic URL
        comicUrl = 'https:' + comicElem[0].get('src')
        print(f'Downloading image {comicUrl}...')
        res = requests.get(comicUrl)
        res.raise_for_status()

        # Save the image to ./xkcd
        imageFileName = os.path.join('xkcd', os.path.basename(comicUrl))
        with open(imageFileName, 'wb') as imageFile:
            for chunk in res.iter_content(100000):
                imageFile.write(chunk)

    # Get the Prev button's URL
    prevLink = soup.select('a[rel="prev"]')[0]
    url = 'http://xkcd.com' + prevLink.get('href')

print('Done.')
